// PE forwards to openvr_api_orig.dll — ACC OpenVR 1.5.17 only.
// Init / GIPA / presence are implemented in proxy-acc.cpp.
#pragma comment(linker, "/export:LiquidVR=openvr_api_orig.LiquidVR")
#pragma comment(linker, "/export:VRCompositorSystemInternal=openvr_api_orig.VRCompositorSystemInternal")
#pragma comment(linker, "/export:VRControlPanel=openvr_api_orig.VRControlPanel")
#pragma comment(linker, "/export:VRDashboardManager=openvr_api_orig.VRDashboardManager")
#pragma comment(linker, "/export:VROculusDirect=openvr_api_orig.VROculusDirect")
#pragma comment(linker, "/export:VROverlayView=openvr_api_orig.VROverlayView")
#pragma comment(linker, "/export:VRPaths=openvr_api_orig.VRPaths")
#pragma comment(linker, "/export:VRRenderModelsInternal=openvr_api_orig.VRRenderModelsInternal")
#pragma comment(linker, "/export:VRSceneGraph=openvr_api_orig.VRSceneGraph")
#pragma comment(linker, "/export:VRTrackedCameraInternal=openvr_api_orig.VRTrackedCameraInternal")
#pragma comment(linker, "/export:VRVirtualDisplay=openvr_api_orig.VRVirtualDisplay")
#pragma comment(linker, "/export:VR_GetInitToken=openvr_api_orig.VR_GetInitToken")
#pragma comment(linker, "/export:VR_GetRuntimePath=openvr_api_orig.VR_GetRuntimePath")
#pragma comment(linker, "/export:VR_GetStringForHmdError=openvr_api_orig.VR_GetStringForHmdError")
#pragma comment(linker, "/export:VR_GetVRInitErrorAsEnglishDescription=openvr_api_orig.VR_GetVRInitErrorAsEnglishDescription")
#pragma comment(linker, "/export:VR_GetVRInitErrorAsSymbol=openvr_api_orig.VR_GetVRInitErrorAsSymbol")
#pragma comment(linker, "/export:VR_IsInterfaceVersionValid=openvr_api_orig.VR_IsInterfaceVersionValid")
#pragma comment(linker, "/export:VR_RuntimePath=openvr_api_orig.VR_RuntimePath")
